<div class="wrapper">
    <div id="content-login" class="container">
        <div class="container">
            <div class="row">
                <div  style="border:1px solid; margin-top:40px;margin-bottom:40px; padding:30px;" class="col-xs-12 col-sm-6 col-md-6 col-md-offset-3 ">
                    <form id="formLogin" class="form-horizontal">
                        <div class="form-group">
                            <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
                            <div class="col-sm-10">
                                <input type="text" name="usuario" class="form-control" id="email" placeholder="Email">
                            </div>
                        </div>
                        <div class="form-group">
                            <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
                            <div class="col-sm-10">
                                <input type="password" class="form-control" id="inputPassword3" name="senha" placeholder="Password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="button" id="efetuarLogin" class="btn btn-default">Sign in</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
