<?= $this->doctype()?>

<html lang="en">
<head>
    <meta charset="utf-8">
    <?= $this->headTitle('ZF Skeleton Dashboard')->setSeparator(' - ')->setAutoEscape(false) ?>

    <?= $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
        ->prependStylesheet($this->basePath('fonts/font-awesome/css/font-awesome.min.css'))
        ->prependStylesheet($this->basePath('css/bootstrap-theme.css'))
        ->prependStylesheet($this->basePath('css/bootstrap.css'))
        ->prependStylesheet($this->basePath('css/style.css'))
        ->prependStylesheet($this->basePath('css/prototype.css'))
    //->prependStylesheet($this->basePath('css/materialize.css'))

    ?>

    <!-- Scripts -->
    <?= $this->headScript()
        ->prependFile($this->basePath('lib/prototype.js'))
        ->prependFile($this->basePath('lib/navigation.js'))
        ->prependFile($this->basePath('lib/service.js'))
        ->prependFile($this->basePath('js/bootstrap.js'))
        ->prependFile($this->basePath('js/materialize.js'))
        ->prependFile($this->basePath('js/jquery-3.2.1.js'))
    ?>
</head>
<body>

<div id="main" class="container-fluid">
    <header>

    </header>
    <div id="content">
        <div id="central-content">
            <?= $this->content ?>
        </div>
    </div>
    <footer class="footer">
        <div class="container-fluid">
            <div class="row">
                <div class="col-md-12">

                </div>
            </div>
        </div>
    </footer>
</div>



</body>
</html>

